---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dmx1
  namespace: homework
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx1
          image: deniss/repository:nginx1
          imagePullPolicy: Always
          ports:
            - name: port
              containerPort: 80
              protocol: TCP
      imagePullSecrets:
        - name: rx2